export const ALL_GET_REQUEST = "ALL_GET_REQUEST";
export const ALL_GET_SUCCESS = "ALL_GET_SUCCESS";
export const ALL_GET_FAIL = "ALL_GET_FAIL";

export const ALL_ABOUT_REQUEST = "ALL_ABOUT_REQUEST";
export const ALL_ABOUT_SUCCESS = "ALL_ABOUT_SUCCESS";
export const ALL_ABOUT_FAIL = "ALL_ABOUT_FAIL";

export const UPDATE_ABOUT_REQUEST = "UPDATE_ABOUT_REQUEST";
export const UPDATE_ABOUT_SUCCESS = "UPDATE_ABOUT_SUCCESS";
export const UPDATE_ABOUT_RESET = "UPDATE_ABOUT_RESET";
export const UPDATE_ABOUT_FAIL = "UPDATE_ABOUT_FAIL";

export const DELETE_ABOUT_REQUEST = "DELETE_ABOUT_REQUEST";
export const DELETE_ABOUT_SUCCESS = "DELETE_ABOUT_SUCCESS";
export const DELETE_ABOUT_RESET = "DELETE_ABOUT_RESET";
export const DELETE_ABOUT_FAIL = "DELETE_ABOUT_FAIL";

export const CREATE_ABOUT_REQUEST = "CREATE_ABOUT_REQUEST";
export const CREATE_ABOUT_SUCCESS = "CREATE_ABOUT_SUCCESS";
export const CREATE_ABOUT_RESET = "CREATE_ABOUT_RESET";
export const CREATE_ABOUT_FAIL = "CREATE_ABOUT_FAIL";

export const GET_ABOUT_REQUEST = "GET_ABOUT_REQUEST";
export const GET_ABOUT_SUCCESS = "GET_ABOUT_SUCCESS";
export const GET_ABOUT_FAIL = "GET_ABOUT_FAIL";

export const ALL_EDUCATION_REQUEST = "ALL_EDUCATION_REQUEST";
export const ALL_EDUCATION_SUCCESS = "ALL_EDUCATION_SUCCESS";
export const ALL_EDUCATION_FAIL = "ALL_EDUCATION_FAIL";

export const UPDATE_EDUCATION_REQUEST = "UPDATE_EDUCATION_REQUEST";
export const UPDATE_EDUCATION_SUCCESS = "UPDATE_EDUCATION_SUCCESS";
export const UPDATE_EDUCATION_RESET = "UPDATE_EDUCATION_RESET";
export const UPDATE_EDUCATION_FAIL = "UPDATE_EDUCATION_FAIL";

export const DELETE_EDUCATION_REQUEST = "DELETE_EDUCATION_REQUEST";
export const DELETE_EDUCATION_SUCCESS = "DELETE_EDUCATION_SUCCESS";
export const DELETE_EDUCATION_RESET = "DELETE_EDUCATION_RESET";
export const DELETE_EDUCATION_FAIL = "DELETE_EDUCATION_FAIL";

export const CREATE_EDUCATION_REQUEST = "CREATE_EDUCATION_REQUEST";
export const CREATE_EDUCATION_SUCCESS = "CREATE_EDUCATION_SUCCESS";
export const CREATE_EDUCATION_RESET = "CREATE_EDUCATION_RESET";
export const CREATE_EDUCATION_FAIL = "CREATE_EDUCATION_FAIL";

export const GET_EDUCATION_REQUEST = "GET_EDUCATION_REQUEST";
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
export const GET_EDUCATION_FAIL = "GET_EDUCATION_FAIL";

export const ADMIN_COUNT_REQUEST = "ADMIN_COUNT_REQUEST";
export const ADMIN_COUNT_SUCCESS = "ADMIN_COUNT_SUCCESS";
export const ADMIN_COUNT_FAIL = "ADMIN_COUNT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
