export const CREATE_MESSAGE_REQUEST = "CREATE_MESSAGE_REQUEST";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_RESET = "CREATE_MESSAGE_RESET";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";

export const ALL_MESSAGE_REQUEST = "ALL_MESSAGE_REQUEST";
export const ALL_MESSAGE_SUCCESS = "ALL_MESSAGE_SUCCESS";
export const ALL_MESSAGE_RESET = "ALL_MESSAGE_RESET";
export const ALL_MESSAGE_FAIL = "ALL_MESSAGE_FAIL";

export const DELETE_MESSAGE_REQUEST = "DELETE_MESSAGE_REQUEST";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_RESET = "DELETE_MESSAGE_RESET";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
